<?php
namespace Shape;
use Interface\Resizeable;
use JetBrains\PhpStorm\Pure;

include "../vendor/autoload.php";
class Squares extends Rectangles
{
    #[Pure] public function __construct($edgeA)
    {
        parent::__construct($edgeA, $edgeA);

    }

    public function calculatorArea(): int|float
    {
        return pow($this->edgeA,2);
    }

    #[Pure] public function resize(float|int $percent): float|int
    {
        return parent::resize($percent); // TODO: Change the autogenerated stub
    }
}